#create_clock -period 40  [get_ports clock]
create_clock -period 10   [get_ports clock]
create_clock -period 11.2 [get_ports clock]

#set_input_delay  -clock clock -min   0 [get_ports -filter {DIRECTION == IN}]
#set_input_delay  -clock clock -max   2 [get_ports -filter {DIRECTION == IN}]
#set_output_delay -clock clock -min   0 [get_ports -filter {DIRECTION == OUT}]
#set_output_delay -clock clock -max   2 [get_ports -filter {DIRECTION == OUT}]

set_input_delay  -clock clock -min   0 [lsearch -all -inline -not -exact [get_ports -filter {DIRECTION == IN}] "clock"]
set_input_delay  -clock clock -max   2 [lsearch -all -inline -not -exact [get_ports -filter {DIRECTION == IN}] "clock"]
set_output_delay -clock clock -min   0 [get_ports -filter {DIRECTION == OUT}]
set_output_delay -clock clock -max   2 [get_ports -filter {DIRECTION == OUT}]

set_property PACKAGE_PIN C15  [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports found]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports stop]
set_property PACKAGE_PIN D18  [get_ports reset]
set_property PACKAGE_PIN D19  [get_ports found]
set_property PACKAGE_PIN G18  [get_ports stop]
set_property PACKAGE_PIN F18  [get_ports {Key[0]}]
set_property PACKAGE_PIN E18  [get_ports {Key[1]}]
set_property PACKAGE_PIN E19  [get_ports {Key[2]}]
set_property PACKAGE_PIN H19  [get_ports {Key[3]}]
set_property PACKAGE_PIN G19  [get_ports {Key[4]}]
set_property PACKAGE_PIN H17  [get_ports {data[0]}]
set_property PACKAGE_PIN G17  [get_ports {data[1]}]
set_property PACKAGE_PIN K19  [get_ports {data[2]}]
set_property PACKAGE_PIN J19  [get_ports {data[3]}]
set_property PACKAGE_PIN J17  [get_ports {Data[0]}]
set_property PACKAGE_PIN J18  [get_ports {Data[1]}]
set_property PACKAGE_PIN L18  [get_ports {Data[2]}]
set_property PACKAGE_PIN K18  [get_ports {Data[3]}]
