create_clock -period 100         [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports found]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Key[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports stop]
set_property PACKAGE_PIN BB39 [get_ports clock]
set_property PACKAGE_PIN AY40 [get_ports reset]
set_property PACKAGE_PIN Y2   [get_ports found]
set_property PACKAGE_PIN Y3   [get_ports stop]
set_property PACKAGE_PIN Y5   [get_ports {Key[0]}]
set_property PACKAGE_PIN Y6   [get_ports {Key[1]}]
set_property PACKAGE_PIN Y7   [get_ports {Key[2]}]
set_property PACKAGE_PIN Y8   [get_ports {Key[3]}]
set_property PACKAGE_PIN Y10  [get_ports {Key[4]}]
set_property PACKAGE_PIN Y30  [get_ports {data[0]}]
set_property PACKAGE_PIN Y31  [get_ports {data[1]}]
set_property PACKAGE_PIN Y32  [get_ports {data[2]}]
set_property PACKAGE_PIN Y33  [get_ports {data[3]}]
set_property PACKAGE_PIN Y35  [get_ports {Data[0]}]
set_property PACKAGE_PIN Y36  [get_ports {Data[1]}]
set_property PACKAGE_PIN Y37  [get_ports {Data[2]}]
set_property PACKAGE_PIN Y38  [get_ports {Data[3]}]

# Set max fan-out for all non-clock signals
# set_property MAX_FANOUT 2 [get_nets]

# Voltage
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
