# Test 2025-03-31 at 04:06:00

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/c.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Install C and dtt
      run: |
         sudo apt install build-essential
         sudo cpan install -T Data::Table::Text GitHub::Crud

    - name: Risc V
      run: |
        sudo apt install gcc-riscv64-unknown-elf libnewlib-dev

    - name: Test
      run: |
        cd c; perl stuck.pl

    - name: Asm
      run: |
        cd c; riscv64-unknown-elf-gcc -S -I. -I/usr/include/newlib/  -o stuck.asm stuck.c
