# Test 2025-03-31 at 03:05:34

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/c.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - uses: philiprbrenan/AppaAppa_dtt_v1@main

    - name: Risc V
      run: |
        sudo apt install gcc-riscv64-unknown-elf libnewlib-dev

    - name: Test
      run: |
        cd c; perl stuck.pl

    - name: Asm
      run: |
        cd c; riscv64-unknown-elf-gcc -S -I. -I/usr/include/newlib/  -o stuck.asm stuck.c
