# Test 2025-03-29 at 23:44:26

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/c.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Risc V
      run: |
        sudo apt install gcc-riscv64-unknown-elf libnewlib-dev

    - name: Test
      run: |
        gcc -fmax-errors=7 -Wall -Wextra -O0 -g3 -I. -o "stuck_test" /home/phil/btreeBlock/c/stuck_test.c && timeout 10s ./stuck_test

    - name: Asm
      run: |
        cd c; riscv64-unknown-elf-gcc -S stuck.c -I. -I/usr/include/newlib/  -o stuck.asm
