# Test 2025-04-05 at 04:56:31

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/c.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Install C and dtt
      run: |
         sudo apt install build-essential
         sudo cpan install -T Data::Table::Text GitHub::Crud

    - name: Risc V
      run: |
        sudo apt install gcc-riscv64-unknown-elf libnewlib-dev

    - name: java
      run: |
        bash j.sh BtreeSF

    - name: asm
      run: |
        cd c; perl riscV.pl
