# Test 2025-04-02 at 04:26:39

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/c.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Install C and dtt
      run: |
         sudo apt install build-essential
         sudo cpan install -T Data::Table::Text GitHub::Crud

    - name: Risc V
      run: |
        sudo apt install gcc-riscv64-unknown-elf libnewlib-dev

    - name: Stuck
      run: |
        cd c; perl stuck.pl

    - name: btree
      run: |
        cd c; gcc -fmax-errors=7 -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-function -O0 -g3 -rdynamic -I. -o "btree" btree.c && timeout 10s ./btree

    - name: Asm
      run: |
        cd c; riscv64-unknown-elf-gcc -S -I. -I/usr/include/newlib/  -o stuck.asm stuck.c
