# Test 2025-04-05 at 05:16:54

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/c.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 24'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Java release
      run: |
        java -version

    - name: Install C and dtt
      run: |
         sudo apt install build-essential
         sudo cpan install -T Data::Table::Text GitHub::Crud

    - name: Risc V
      run: |
        sudo apt install gcc-riscv64-unknown-elf libnewlib-dev

    - name: Asm
      run: |
        cd c; perl riscV.pl
