# Test 2025-03-08 at 22:22:01

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Layout, MemoryLayoutDM]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Verilog install
      if: matrix.task == 'BtreePA'
      run: |
        sudo apt install iverilog

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp `find .  -name "*.java"` com/AppaApps/Silicon

    - name: Files
      run:
        tree

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes `find com/AppaApps/Silicon -name "*.java"`

    - name: Test Layout
      if: matrix.task == 'Layout'
      run: |
        java -cp Classes com/AppaApps/Silicon/Layout


    - name: Test MemoryLayoutDM
      if: matrix.task == 'MemoryLayoutDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/MemoryLayoutDM

