# Test 2025-03-08 at 03:15:56

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [BtreePA, Memory, MemoryLayoutDM]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Verilog install
      if: matrix.task == 'BtreePA'
      run: |
        sudo apt install iverilog

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp BtreePA, Memory, MemoryLayoutDM com/AppaApps/Silicon

    - name: Files
      run:
        tree

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes `find com/AppaApps/Silicon -name "*.java"`

    - name: Test BtreePA
      if: matrix.task == 'BtreePA'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreePA


    - name: Test Memory
      if: matrix.task == 'Memory'
      run: |
        java -cp Classes com/AppaApps/Silicon/Memory


    - name: Test MemoryLayoutDM
      if: matrix.task == 'MemoryLayoutDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/MemoryLayoutDM

