    - name: Verilog install
      run: |
        sudo apt install iverilog

    - name: Verilog Run
      run: |
        rm -f doc; iverilog -Iverilog/includes/ -g2012 -o doc verilog/doc.sv verilog/doc.tb && timeout 1m ./doc
