# Test 2025-04-09 at 09:35:57

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [BtreeSF, BtreeDM, BtreeBam]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 24'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Java release
      run: |
        java -version

    - name: Verilog install
      run: |
        sudo apt install iverilog

    - name: Verilog release
      run: |
        iverilog -V

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp *.java com/AppaApps/Silicon

    - name: Java
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/*.java

    - name: Test BtreeSF
      if: matrix.task == 'BtreeSF'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeSF


    - name: Test BtreeDM
      if: matrix.task == 'BtreeDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeDM


    - name: Test BtreeBam
      if: matrix.task == 'BtreeBam'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeBam

