# Test 2025-03-19 at 03:04:53

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Btree, BtreeDM, BtreePA, BtreeSA, BtreeSML, BtreeSP, BtreeStuck, BtreeStuckStatic, If, Layout, Memory, MemoryLayout, MemoryLayoutDM, MemoryLayoutPA, Program, ProgramDM, ProgramPA, StringToNumbers, Stuck, StuckDM, StuckPA, StuckSA, StuckSML, StuckSP, StuckStatic, Test, Verilog]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Verilog install
      run: |
        sudo apt install iverilog

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp `find .  -name "*.java"` com/AppaApps/Silicon

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes `find com/AppaApps/Silicon -name "*.java"`

    - name: Test Btree
      if: matrix.task == 'Btree'
      run: |
        java -cp Classes com/AppaApps/Silicon/Btree


    - name: Test BtreeDM
      if: matrix.task == 'BtreeDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeDM


    - name: Test BtreePA
      if: matrix.task == 'BtreePA'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreePA


    - name: Test BtreeSA
      if: matrix.task == 'BtreeSA'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeSA


    - name: Test BtreeSML
      if: matrix.task == 'BtreeSML'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeSML


    - name: Test BtreeSP
      if: matrix.task == 'BtreeSP'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeSP


    - name: Test BtreeStuck
      if: matrix.task == 'BtreeStuck'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeStuck


    - name: Test BtreeStuckStatic
      if: matrix.task == 'BtreeStuckStatic'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeStuckStatic


    - name: Test If
      if: matrix.task == 'If'
      run: |
        java -cp Classes com/AppaApps/Silicon/If


    - name: Test Layout
      if: matrix.task == 'Layout'
      run: |
        java -cp Classes com/AppaApps/Silicon/Layout


    - name: Test Memory
      if: matrix.task == 'Memory'
      run: |
        java -cp Classes com/AppaApps/Silicon/Memory


    - name: Test MemoryLayout
      if: matrix.task == 'MemoryLayout'
      run: |
        java -cp Classes com/AppaApps/Silicon/MemoryLayout


    - name: Test MemoryLayoutDM
      if: matrix.task == 'MemoryLayoutDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/MemoryLayoutDM


    - name: Test MemoryLayoutPA
      if: matrix.task == 'MemoryLayoutPA'
      run: |
        java -cp Classes com/AppaApps/Silicon/MemoryLayoutPA


    - name: Test Program
      if: matrix.task == 'Program'
      run: |
        java -cp Classes com/AppaApps/Silicon/Program


    - name: Test ProgramDM
      if: matrix.task == 'ProgramDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/ProgramDM


    - name: Test ProgramPA
      if: matrix.task == 'ProgramPA'
      run: |
        java -cp Classes com/AppaApps/Silicon/ProgramPA


    - name: Test StringToNumbers
      if: matrix.task == 'StringToNumbers'
      run: |
        java -cp Classes com/AppaApps/Silicon/StringToNumbers


    - name: Test Stuck
      if: matrix.task == 'Stuck'
      run: |
        java -cp Classes com/AppaApps/Silicon/Stuck


    - name: Test StuckDM
      if: matrix.task == 'StuckDM'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckDM


    - name: Test StuckPA
      if: matrix.task == 'StuckPA'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckPA


    - name: Test StuckSA
      if: matrix.task == 'StuckSA'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckSA


    - name: Test StuckSML
      if: matrix.task == 'StuckSML'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckSML


    - name: Test StuckSP
      if: matrix.task == 'StuckSP'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckSP


    - name: Test StuckStatic
      if: matrix.task == 'StuckStatic'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckStatic


    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -cp Classes com/AppaApps/Silicon/Test


    - name: Test Verilog
      if: matrix.task == 'Verilog'
      run: |
        java -cp Classes com/AppaApps/Silicon/Verilog

