# Test 2024-11-20 at 04:45:49

name: Test
run-name: btreeBlock

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Btree, BtreeStuck, BtreeStuckStatic, Layout, Memory, MemoryLayout, Stuck, StuckStatic, Test]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp `find .  -name "*.java"` com/AppaApps/Silicon

    - name: Files
      run:
        tree

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes `find com/AppaApps/Silicon -name "*.java"`

    - name: Test Btree
      if: matrix.task == 'Btree'
      run: |
        java -cp Classes com/AppaApps/Silicon/Btree

    - name: Test BtreeStuck
      if: matrix.task == 'BtreeStuck'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeStuck

    - name: Test BtreeStuckStatic
      if: matrix.task == 'BtreeStuckStatic'
      run: |
        java -cp Classes com/AppaApps/Silicon/BtreeStuckStatic

    - name: Test Layout
      if: matrix.task == 'Layout'
      run: |
        java -cp Classes com/AppaApps/Silicon/Layout

    - name: Test Memory
      if: matrix.task == 'Memory'
      run: |
        java -cp Classes com/AppaApps/Silicon/Memory

    - name: Test MemoryLayout
      if: matrix.task == 'MemoryLayout'
      run: |
        java -cp Classes com/AppaApps/Silicon/MemoryLayout

    - name: Test Stuck
      if: matrix.task == 'Stuck'
      run: |
        java -cp Classes com/AppaApps/Silicon/Stuck

    - name: Test StuckStatic
      if: matrix.task == 'StuckStatic'
      run: |
        java -cp Classes com/AppaApps/Silicon/StuckStatic

    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -cp Classes com/AppaApps/Silicon/Test
